version: "2"
services:

  postgres:
    image: postgres:9.2
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=TCrGaanoC2s7gT

  zookeeper:
    container_name: zookeeper
    image: znly/zookeeper:3.4.8
    environment:
      - ZOO_ID=1
      - ZOO_SERVERS=zookeeper

  # volume only container for druid
  druid-vols:
    image: deitch/druid:0.9.2
    volumes:
      - druid-vols:/var/druid/segments
      - druid-vols:/var/druid/indexing-logs

  overlord:
    image: deitch/druid:0.9.2
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
    volumes_from:
      - druid-vols
    command:
      - overlord
    ports:
      - "8090:8090"
  coordinator:
    image: deitch/druid:0.9.2
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
    volumes_from:
      - druid-vols
    command:
      - coordinator
    ports:
      - "8081:8081"

  middlemanager:
    image: deitch/druid:0.9.2
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
    volumes_from:
      - druid-vols
    command:
      - middleManager
    ports:
      - "8091:8091"
  historical:
    image: deitch/druid:0.9.2
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
    volumes_from:
      - druid-vols
    command:
      - historical
    ports:
      - "8083:8083"
  broker:
    image: deitch/druid:0.9.2
    environment:
      - DRUID_XMX=1g
      - DRUID_XMS=1g
      - DRUID_MAXNEWSIZE=250m
      - DRUID_NEWSIZE=250m
    volumes_from:
      - druid-vols
    command:
      - broker
    ports:
      - "8082:8082"
volumes:
  druid-vols: